### ISSUE TITLE
Следите за подсказками pycharm 

### ISSUE THREAD

**Issue by Muxamedin** [AlexLaros/lessons_py#1]
поправте отступ в inline коментари в строке:
https://github.com/AlexLaros/lessons_py/blob/64dbcf3013e5d38366608f2b6d90bec20aa6e5d8/lesson_3/task_2.py#L2

**Comment by AlexLaros** [comment]
Исправил:
https://github.com/AlexLaros/lessons_py/blob/master/lesson_3/task_2.py

ср, 17 нояб. 2021 г. в 10:47, Mikel Bily ***@***.***>:
