### ISSUE TITLE
Программа не выполняет до конца условия задачи 

### ISSUE THREAD

**Issue by Muxamedin** [AlexLaros/lessons_py#2]
https://github.com/AlexLaros/lessons_py/blob/d7abe2cbe71e4791ca2036ae3124d27defb79e07/lesson_4/task_4.py#L5
![image](https://user-images.githubusercontent.com/4419752/142770746-90a7cde2-1992-4742-b6e6-d8232cbc3b56.png)

Программа не проверяет что введено имено 2 слова 
Программа не учитывает что могут быть введено больше пробелов чем один(можно на это не обращать пока внимание)
Но еслия введу много слов и после первого идет несколько пробелов то обраьатывеется тлько одно слово 
при выводетой строки что было введено пользователем -  почему то все слова  переводятся автоматически к первой заглавной букве 

![image](https://user-images.githubusercontent.com/4419752/142770913-968d5b05-88d9-4260-b89a-026bcfdccdcf.png)

**Comment by AlexLaros** [comment]
вс, 21 нояб. 2021 г. в 18:41, Mikel Bily ***@***.***>:

**Comment by AlexLaros** [comment]
Сделаю оптимизацию кода, чтобы определялось, что введено именно два слова.
И подскажите задача засчитана?

вс, 21 нояб. 2021 г. в 18:41, Mikel Bily ***@***.***>:

**Comment by Muxamedin** [comment]
Остальное в задаче вроде работает 
Так как проверка на 2 слова  - это одно из требований к задачи то я немого сказать что она готова. 

Mikel Bily
Staff Software Engineer
CloudBees, Inc.

**Comment by AlexLaros** [comment]
Тогда я доделаю

вс, 21 нояб. 2021 г. в 19:09, Mikel Bily ***@***.***>:

> Остальное в задаче вроде работает
> Так как проверка на 2 слова - это одно из требований к задачи то я немого
> сказать что она готова.
>
> Mikel Bily
> Staff Software Engineer
> CloudBees, Inc.
>
>
>
>

**Comment by AlexLaros** [comment]
Остальные задачи правильны?

вс, 21 нояб. 2021 г. в 19:12, Александр Гвоздев ***@***.***>:

> Тогда я доделаю
>
> вс, 21 нояб. 2021 г. в 19:09, Mikel Bily ***@***.***>:
>
>> Остальное в задаче вроде работает
>> Так как проверка на 2 слова - это одно из требований к задачи то я немого
>> сказать что она готова.
>>
>> Mikel Bily
>> Staff Software Engineer
>> CloudBees, Inc.
>>
>>
>>
>>

**Comment by AlexLaros** [comment]
Исправил функцию проверки на ввод двух слов, теперь работает корректно.
Кроме, того, если пользователь введет по одному символу, это будет
считаться за неправильный ввод,.Однако,
если будет введена строка, например: "Я Саша" - её функция посчитает
правильно введенной. И так далее, я посчитал так правильней всего, так как
в некоторых исключительных случаях слова могут состоять из одной буквы:
например, местоимение "я" - в русском и так же в английском - "I".

вс, 21 нояб. 2021 г. в 18:41, Mikel Bily ***@***.***>:
