### ISSUE TITLE
Проверка нужно подправить

### ISSUE THREAD

**Issue by Muxamedin** [AlexLaros/lessons_py#3]
https://github.com/AlexLaros/lessons_py/blob/d7abe2cbe71e4791ca2036ae3124d27defb79e07/lesson_4/task_5.py#L4
![image](https://user-images.githubusercontent.com/4419752/142771118-67d221b3-6666-4ddc-bc12-ce61de37e9e1.png)
Если не ввести строку - а сразу нажать  enter - то проверка на количество букв не отрабатывает

**Comment by AlexLaros** [comment]
Исправлю

вс, 21 нояб. 2021 г. в 18:47, Mikel Bily ***@***.***>:
