### ISSUE TITLE
Обратите внимание на рекомендации pycharm 

### ISSUE THREAD

**Issue by Muxamedin** [AlexLaros/lessons_py#5]
https://github.com/AlexLaros/lessons_py/blob/03278d824b2749e8d0bb1405d8db981c399b0516/lesson_6/task_1.py#L1
![image](https://user-images.githubusercontent.com/4419752/144681100-b57ab068-cba7-4d83-9f78-8f00944c2eda.png)

**Comment by Muxamedin** [comment]
Если в коде вот этом 
![image](https://user-images.githubusercontent.com/4419752/144681439-f02e4b59-6df2-437a-b303-6330b67c0054.png)
исправить вот так 
![image](https://user-images.githubusercontent.com/4419752/144681412-b1f57351-c205-49ab-88ac-adc9188ea072.png)

то вы не заметите разницу в выводе 
но получите  оформление согласно требований

**Comment by AlexLaros** [comment]
Понял, откорректирую согласно PEP8

**Comment by Muxamedin** [comment]
![Uploading image.png…]()

**Comment by AlexLaros** [comment]
Отредактировал длинные строки

**Comment by AlexLaros** [comment]
У меня почему-то мой PyCharm не отмечает такого рода ошибок
