### ISSUE TITLE
Разбежность с требованиями к задачи 

### ISSUE THREAD

**Issue by Muxamedin** [AlexLaros/lessons_py#6]
![image](https://user-images.githubusercontent.com/4419752/144682499-91bc91f7-bd91-4c68-b2b2-bbc0a860a33b.png)

https://github.com/AlexLaros/lessons_py/blob/d4d6ebb0c364d5895dddf600abec786efe29e942/lesson_6/task_2.py#L23

срезы создают таки новый список 

модифицировав этот код не сложно убедится 
<img width="960" alt="Screen Shot 2021-12-04 at 00 45 05" src="https://user-images.githubusercontent.com/4419752/144682665-b14f530a-751d-4920-bedc-e95261f709dc.png">

**Comment by AlexLaros** [comment]
Исправил

**Comment by AlexLaros** [comment]
![Снимок](https://user-images.githubusercontent.com/94188621/144687231-ec8c47c3-05cc-4741-8963-8f593662caf5.PNG)
