### ISSUE TITLE
Форматирование 

### ISSUE THREAD

**Issue by Muxamedin** [AlexLaros/lessons_py#7]
https://github.com/AlexLaros/lessons_py/blob/7a7f070e7b3d24b2fa5f1fa49b0a0b6c90c6a87b/lesson_9/task_1.py#L2
![image](https://user-images.githubusercontent.com/4419752/146653179-93e0b8b4-2c94-4c45-8380-c15c22fc4e91.png)

**Comment by AlexLaros** [comment]
Ctrl+Alt+L возможно решит проблему. У меня никаких ошибок. Табуляция равномерная во всех строках кода.

**Comment by AlexLaros** [comment]
Обновил код файла "task_1.py"
